// <auto-generated />
using Bourque.GridUpload.Data.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bourque.GridUpload.Data.EntityFramework.Migrations
{
    [DbContext(typeof(GridUploadContext))]
    [Migration("20220104125908_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Bourque.GridUpload.Data.Models.DbModels.ApplicationCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ApplicationName")
                        .HasColumnType("int")
                        .HasColumnName("application_name");

                    b.HasKey("Id");

                    b.ToTable("GRID_UPLOAD_APPLICATION_CODE", (string)null);
                });

            modelBuilder.Entity("Bourque.GridUpload.Data.Models.DbModels.ColumnMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ColumnCellName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("column_cell_name");

                    b.Property<string>("ColumnDataType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("column_data_type");

                    b.Property<string>("ColumnDisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("column_display_name");

                    b.HasKey("Id");

                    b.ToTable("GRID_UPLOAD_COLUMN_METADATA", (string)null);
                });

            modelBuilder.Entity("Bourque.GridUpload.Data.Models.DbModels.ColumnMetadataApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int")
                        .HasColumnName("application_id")
                        .HasColumnOrder(0);

                    b.Property<int>("ColumnMetadataId")
                        .HasColumnType("int")
                        .HasColumnName("column_metadata_id")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("ColumnMetadataId");

                    b.ToTable("GRID_UPLOAD_COLUMN_METADATA_APPLICATION", (string)null);
                });

            modelBuilder.Entity("Bourque.GridUpload.Data.Models.DbModels.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("entity_name");

                    b.Property<string>("ProcessURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("process_url");

                    b.Property<string>("ValidateURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("validate_url");

                    b.HasKey("Id");

                    b.ToTable("GRID_UPLOAD_ENTITY", (string)null);
                });

            modelBuilder.Entity("Bourque.GridUpload.Data.Models.DbModels.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("TemplateDisplayName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("template_display_name");

                    b.Property<string>("TemplateOwner")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("template_owner");

                    b.HasKey("Id");

                    b.ToTable("GRID_UPLOAD_TEMPLATE", (string)null);
                });

            modelBuilder.Entity("Bourque.GridUpload.Data.Models.DbModels.TemplateApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int")
                        .HasColumnName("application_id")
                        .HasColumnOrder(0);

                    b.Property<int>("TemplateId")
                        .HasColumnType("int")
                        .HasColumnName("template_id")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("TemplateId");

                    b.ToTable("GRID_UPLOAD_TEMPLATE_APPLICATION", (string)null);
                });

            modelBuilder.Entity("Bourque.GridUpload.Data.Models.DbModels.TemplateColumn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ColumnMetadataId")
                        .HasColumnType("int")
                        .HasColumnName("column_metadata_id")
                        .HasColumnOrder(1);

                    b.Property<int>("Position")
                        .HasColumnType("int")
                        .HasColumnName("position");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int")
                        .HasColumnName("template_id")
                        .HasColumnOrder(0);

                    b.HasKey("Id");

                    b.HasIndex("ColumnMetadataId");

                    b.HasIndex("TemplateId");

                    b.ToTable("GRID_UPLOAD_TEMPLATE_COLUMN", (string)null);
                });

            modelBuilder.Entity("Bourque.GridUpload.Data.Models.DbModels.TemplateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("EntityId")
                        .HasColumnType("int")
                        .HasColumnName("entity_id")
                        .HasColumnOrder(0);

                    b.Property<int>("TemplateId")
                        .HasColumnType("int")
                        .HasColumnName("template_id")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("TemplateId");

                    b.ToTable("GRID_UPLOAD_TEMPLATE_ENTITY", (string)null);
                });

            modelBuilder.Entity("Bourque.GridUpload.Data.Models.DbModels.ColumnMetadataApplication", b =>
                {
                    b.HasOne("Bourque.GridUpload.Data.Models.DbModels.ApplicationCode", "ApplicationCode")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bourque.GridUpload.Data.Models.DbModels.ColumnMetadata", "ColumnMetadata")
                        .WithMany()
                        .HasForeignKey("ColumnMetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationCode");

                    b.Navigation("ColumnMetadata");
                });

            modelBuilder.Entity("Bourque.GridUpload.Data.Models.DbModels.TemplateApplication", b =>
                {
                    b.HasOne("Bourque.GridUpload.Data.Models.DbModels.ApplicationCode", "ApplicationCode")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bourque.GridUpload.Data.Models.DbModels.Template", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationCode");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Bourque.GridUpload.Data.Models.DbModels.TemplateColumn", b =>
                {
                    b.HasOne("Bourque.GridUpload.Data.Models.DbModels.ColumnMetadata", "ColumnMetadata")
                        .WithMany()
                        .HasForeignKey("ColumnMetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bourque.GridUpload.Data.Models.DbModels.Template", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ColumnMetadata");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Bourque.GridUpload.Data.Models.DbModels.TemplateEntity", b =>
                {
                    b.HasOne("Bourque.GridUpload.Data.Models.DbModels.Entity", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bourque.GridUpload.Data.Models.DbModels.Template", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("Template");
                });
#pragma warning restore 612, 618
        }
    }
}
